### ISSUE TITLE
Device node doesn't show up with kernel 4.19.38

### ISSUE THREAD

**Issue by stashlukj** [mvduin/py-uio#7]
I've enabled uio_pruss driver in the kernel, and modified the device tree to match the changes in AM335X-PRU-UIO-00A0.dtbo.

The `/dev/uio` nodes do not appear, and no messages appear in dmesg.
I've tried to `modprobe uio_pruss`, which shows up in `lsmod`, but still nothing happens. Am I missing something obvious?

**Comment by mvduin** [comment]
Apologies for the slow response.  For some reason gmail didn't feel like marking the github notification as "important", so I missed it.

You should not need to manually modprobe a device driver on linux, it should get loaded automatically (unless e.g. your module index is broken).  If it didn't get loaded, it's because the kernel didn't feel like it had any need for it, which is reaffirmed by the fact that modprobing it manually resulted in no devices (i.e. it continued to not see any use for the driver after it was loaded).

It sounds like you're not using a standard beaglebone kernel?  The uio_pruss driver in mainline linux does not support AM335x.  To fix that you need these two partches:
https://github.com/RobertCNelson/bb-kernel/blob/am33x-v4.19/patches/drivers/ti/uio_pruss/0001-uio-pruss-cleanups-and-pruss-v2-pru-icss-support.patch
https://github.com/RobertCNelson/bb-kernel/blob/am33x-v4.19/patches/drivers/ti/uio_pruss/0003-ARM-omap2-support-deasserting-reset-from-dts.patch

**Comment by stashlukj** [comment]
Thanks for taking a look at this. I did try the patches you mentioned with the ti,pruss-v2 compatible pruss entry in the device tree. I'm back-porting an X15 solution using ti-linux-kernel-dev 4.14.y to a CriticalLink MitySOM AM335x using mainline 4.19.38. There were some additions to am33xx.dtsi with regard to the PRU in mainline 4.19.35 which were different than the ti,pruss-v2.
