### ISSUE TITLE
No such file or directory: '/dev/uio/pruss/module

### ISSUE THREAD

**Issue by atmelletje** [mvduin/py-uio#8]
hallo Matthijs,
Kheb een issue als ik een py sample file wil starten.

Traceback (most recent call last):
  File "/var/lib/cloud9/py-uio/pru-examples/basic-test.py", line 5, in <module>
    pruss = Icss( "/dev/uio/pruss/module" )
  File "/var/lib/cloud9/py-uio/src/uio/ti/icss/__init__.py", line 16, in __init__
    super().__init__( path )
  File "/var/lib/cloud9/py-uio/src/uio/device.py", line 165, in __init__
    self._fd = os.open( str(path), flags )
FileNotFoundError: [Errno 2] No such file or directory: '/dev/uio/pruss/module'

Process exited with code: 1

herken je de fout en zou je me verder kunnen helpen? mogekijk zie ik de uitleg niet helemaal duidelijk voor me, hoewel alles verder best makkelijk te doen was. 

Roel

**Comment by mvduin** [comment]
If no uio devices (e.g. `/dev/uio0`) exist at all then probably pruss is configured to use remoteproc rather than uio; this selection is controlled through the `uboot_overlay_pru` variable in /boot/uEnv.txt.
If uio devices exist but the `/dev/uio/` directory does not then you're missing the udev rules file that creates convenient symlinks, or neglected to update initramfs after installing this file.

These steps are all in the [installation instructions in the README](https://github.com/mvduin/py-uio#uio_pruss).

**Comment by atmelletje** [comment]
Matthijs, 
the Pru example files are working without issues. This means that the installation ( was / should be ) successful. ?! :)  hardware,, now the more fun part is going to start. 

Roel
